name: safe_browser
description: SafeBrowse - a privacy-focused browser for Windows and Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
